# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gquil < Formula
  desc "Inspect, visualize, and transform GraphQL schemas on the command line."
  homepage "https://github.com/benweint/gquil"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/benweint/gquil/releases/download/v0.2.3/gquil_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "45aaf06cc882f1f336107d555926f7ec25e673aea10c85ab2a4364afaa01b0f5"

      def install
        bin.install "gquil"
      end
    end
    on_arm do
      url "https://github.com/benweint/gquil/releases/download/v0.2.3/gquil_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "559ace3f3f6bfc6ebf068168e3c9f25d0a7bae63b98570fea2413cb5c8987aa7"

      def install
        bin.install "gquil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.2.3/gquil_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "66f193b1958b04d6c2545a7057b2498a0fdbdb57f620446fe28f3d83add92b79"

        def install
          bin.install "gquil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.2.3/gquil_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "b95f2f4c45c58848f3ac58d27219570d84d835481c1b1cb3922ae1d3c26f659f"

        def install
          bin.install "gquil"
        end
      end
    end
  end

  test do
    system "#{bin}/gquil --version"
  end
end
