# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gquil < Formula
  desc "Inspect, visualize, and transform GraphQL schemas on the command line."
  homepage "https://github.com/benweint/gquil"
  version "0.1.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/benweint/gquil/releases/download/v0.1.9/gquil_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "9845d09721810a0dd677b7b53baa4d713656e9ce7737ad2f2d1e406506f24b80"

      def install
        bin.install "gquil"
      end
    end
    on_arm do
      url "https://github.com/benweint/gquil/releases/download/v0.1.9/gquil_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d465ab2109fe58a7258b21f899661b46dafce1f8597848d6b10c84ed779be1a2"

      def install
        bin.install "gquil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.1.9/gquil_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "1d92722eb19839c53de8fd39c87ab8a23e91b849a8e6ddca8e9a92490179e53f"

        def install
          bin.install "gquil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.1.9/gquil_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "d75cd5ebbcb480de31cb8a2d2f6f31727d3d3adf982258ea82b5e65b8ac888f0"

        def install
          bin.install "gquil"
        end
      end
    end
  end

  test do
    system "#{bin}/gquil --version"
  end
end
