# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gquil < Formula
  desc "Inspect, visualize, and transform GraphQL schemas on the command line."
  homepage "https://github.com/benweint/gquil"
  version "0.1.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/benweint/gquil/releases/download/v0.1.10/gquil_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "7beceb659f165369651237be9db736397e7fbde7c69caa031f19362aea7020b8"

      def install
        bin.install "gquil"
      end
    end
    on_arm do
      url "https://github.com/benweint/gquil/releases/download/v0.1.10/gquil_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4aa63aa822fb637d5df5158c7a0f8535dc1969237492fe0c3eeb4b20625e73ec"

      def install
        bin.install "gquil"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.1.10/gquil_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "227b848c8fb14356c0b6dba3bf756eddc9033734becaad246d28b06fc19efe4a"

        def install
          bin.install "gquil"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/benweint/gquil/releases/download/v0.1.10/gquil_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ad9304804fcf3562c9c42a314d8bb6f238f98a223757cf50db32117a94e8ae73"

        def install
          bin.install "gquil"
        end
      end
    end
  end

  test do
    system "#{bin}/gquil --version"
  end
end
