name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build (darwin amd64)
      run: go build -v -o gquil_darwin_amd64 ./cmd/gquil.go
      env:
        GOOS: darwin
        GOARCH: amd64

    - name: Build (darwin arm64)
      run: go build -v -o gquil_darwin_arm64 ./cmd/gquil.go
      env:
        GOOS: darwin
        GOARCH: arm64

    - name: Build (linux amd64)
      run: go build -v -o gquil_linux_amd64 ./cmd/gquil.go
      env:
        GOOS: darwin
        GOARCH: amd64

    - name: Build (linux arm64)
      run: go build -v -o gquil_linux_arm64 ./cmd/gquil.go
      env:
        GOOS: darwin
        GOARCH: arm64

    - run: |
        sha256sum gquil_* >checksums.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "gquil_*,checksums.txt"
